/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Converter;
import Converter.*;

public class App {

    public static void main(String[] args) {

        Exchange_rate exchange_rate = new Exchange_rate();
    }
}
